# Generated by Django 3.2.9 on 2024-05-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Not Paid'), (2, 'Paid')], default=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.admin')),
            ],
        ),
    ]
