# Generated by Django 3.2.9 on 2024-05-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
