# Generated by Django 3.2.9 on 2024-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
