# Generated by Django 3.2.9 on 2024-05-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_prettynum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrettyNum',
        ),
    ]
