# Generated by Django 3.2.9 on 2024-05-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_delete_prettynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1)),
                ('status', models.SmallIntegerField(choices=[(1, 'Occupied'), (2, 'Not Occupied')], default=2)),
            ],
        ),
    ]
